services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=todo_app
      - DB_USERNAME=root
      - DB_PASSWORD=secret

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/todo:/app
      - /todo/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true  # この行を追加
      - WDS_SOCKET_PORT=0  # この行を追加
      - FAST_REFRESH=false 
    tty: true
    

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: